openapi: 3.0.2
info:
  title: RRS Service API
  version: 1.0.0
  description: >
    The RRS Service API provides detailed information about available zones.
    This endpoint returns the number of masters, workers, storage nodes, and an array
    of rack xnames for each zone. Note: This API is deployed behind an Istio VirtualService
    that rewrites paths (e.g. from /apis/ims/ to /) for proper routing.
servers:
  - url: 'http://localhost:8080'
    description: Backend server for the RRS service
paths:
  /zones:
    get:
      summary: Retrieve Zone Information
      description: >
        Returns a list of zones with detailed properties including the counts of master,
        worker, and storage nodes, along with an array of rack xnames for each zone.
      operationId: getZones
      responses:
        '200':
          description: A list of zones retrieved successfully.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Zone'
              examples:
                sample:
                  value:
                    - zone-name: "zone1"
                      no_of_masters: 1
                      no_of_workers: 1
                      no_of_storage: 0
                      rack-xname: ["unknown"]
                    - zone-name: "zone2"
                      no_of_masters: 1
                      no_of_workers: 1
                      no_of_storage: 0
                      rack-xname: ["unknown"]
                    - zone-name: "zone3"
                      no_of_masters: 1
                      no_of_workers: 2
                      no_of_storage: 0
                      rack-xname: ["unknown"]
        '404':
          description: Resource Not Found - No zones were found.
        '500':
          description: Internal Server Error
components:
  schemas:
    Zone:
      type: object
      properties:
        zone-name:
          type: string
          description: The unique name identifier for the zone.
          example: "zone1"
        no_of_masters:
          type: integer
          description: The number of master nodes in the zone.
          example: 1
        no_of_workers:
          type: integer
          description: The number of worker nodes in the zone.
          example: 1
        no_of_storage:
          type: integer
          description: The number of storage nodes in the zone.
          example: 0
        rack-xname:
          type: array
          items:
            type: string
          description: An array of rack xnames associated with the zone.
          example: ["unknown"]
